version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: monthly
  # Enable updates for github actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
