name: semver-action
description: A github action to find the next semver tag based on current existing tags
author: Breach AS
inputs:
  release:
    required: false
    description: Defines if major, minor or patch should be bumped
    default: 'patch'
  pre-release:
    required: false
    description: True if this should be a pre-release
    default: false
outputs:
  version:
    description: The calculated new version tag to use

branding:
  icon: 'upload-cloud'
  color: 'blue'

runs:
  using: 'node16'
  main: 'index.js' # Entrypoint of action