name: Test Action

on:
  workflow_dispatch:
  push:
    branches:
      - next

jobs:
  test-action:
    name: Create next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          release: 'minor'
          pre-release: true