name: Test Action

on:
  push:
    branches:
      - next

jobs:
  test-action:
    name: Create next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout the main repo
      - uses: actions/checkout@v2 # Grab the package from next and place it here
        with:
          ref: 'next'
          path: './github/actions/'
      - uses: ./github/actions/
        with:
          release: 'minor'
          pre-release: true